### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by jongirard** [reeli/sketch-svg-to-react-component#2]
I have been using this plugin for a while, but recently every time I attempt to either a) export as react component or b) export as RN component I see "something went wrong" only now.

I have uninstalled/reinstalled the plugin and updated Sketch to the latest version.

**Comment by johnwcassidy** [comment]
I'm experiencing this as well, I'm assuming it has to do with more locked down access to adding to the clipboard from Sketch (or the plugin itself). Is there some access that can be granted from the OS to allow this?

**Comment by reeli** [comment]
Please make sure your sketch have access to `Files and Folders`. Go to System Preferences/Security & Privacy/Privacy/Files and Folders, find sketch and click allow.
![image](https://user-images.githubusercontent.com/8966348/117393557-f50fbf00-af26-11eb-8c87-63f22d33da43.png)
